on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '22'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Build Android (APK)
      - run: flutter build apk --debug --split-per-abi

      # Build iOS
      # - run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload

      # Build Windows
      - run: flutter build windows --debug

      # Build Web
      - run: flutter build web --debug

      # Push to Debug
      - name: Push to Debug
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/debug/*,
            build/ios/iphoneos/app.ipa,
            build/windows/runner/Debug/*,
            build/web/*
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}